# Introduction

In [1]:
'''
1. Pytorch Framework - Tensors datatypes
Tensors are similar to numpy arrays, tensors can run on gpus where as numpy arrays cannot run on gpus.
Tenors support Automatic Differentiation
'''

'\n1. Pytorch Framework - Tensors datatypes\nTensors are similar to numpy arrays, tensors can run on gpus where as numpy arrays cannot run on gpus.\nTenors support Automatic Differentiation\n'

# initializing a Tensor

In [2]:
import torch
import numpy as np

In [3]:
torch_tensor = torch.Tensor([[1,2],[3,4]])
print('type = ',type(torch_tensor))
#if we want to convert the tensor to numpy array
numpy_convert = np.array(torch_tensor)
print("type = ",type(numpy_convert))
#further converting nparray to tensor
torch_tensor = torch.tensor(numpy_convert)
print('type = ',type(torch_tensor))




type =  <class 'torch.Tensor'>
type =  <class 'numpy.ndarray'>
type =  <class 'torch.Tensor'>


# Create a tensor of all ones similar to x_tensor

In [4]:
x_ones = torch.ones((2,2))
x_ones

tensor([[1., 1.],
        [1., 1.]])

In [5]:
#Create a new tensor of same shape as existing tensor
x_ones = torch.ones_like(torch_tensor)
x_ones

tensor([[1., 1.],
        [1., 1.]])

In [6]:
#Create a random tensor
x_rand = torch.rand((2,2),dtype = torch.float)
x_rand

tensor([[0.7953, 0.4392],
        [0.6998, 0.0860]])

In [7]:
#Create a new random tensor of same shape as existing tensor
x_rand = torch.rand_like(torch_tensor,dtype = torch.float)
x_rand

tensor([[0.3475, 0.4374],
        [0.5202, 0.6625]])

In [8]:
x_rand.shape

torch.Size([2, 2])

In [9]:
x_rand.dtype

torch.float32

In [10]:
x_rand.device

device(type='cpu')

In [11]:
if torch.cuda.is_available():
  x_rand = x_rand.to('cuda')
else:
  pass

In [12]:
x_rand

tensor([[0.3475, 0.4374],
        [0.5202, 0.6625]], device='cuda:0')

In [13]:
x_rand.device

device(type='cuda', index=0)

# Indexing

In [14]:
tensor = torch.ones((4,4))
print(tensor)
tensor[0] #first row

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


tensor([1., 1., 1., 1.])

In [15]:
tensor[-1] #last row

tensor([1., 1., 1., 1.])

In [16]:
tensor[:,2] #thirt column

tensor([1., 1., 1., 1.])

In [17]:
tensor[[1,2],2:]

tensor([[1., 1.],
        [1., 1.]])

# Concartenating the tensor

In [18]:
tensor = torch.rand(4,4)
tensor

tensor([[0.4618, 0.3658, 0.2106, 0.7026],
        [0.1488, 0.5192, 0.2418, 0.0043],
        [0.3612, 0.5849, 0.8287, 0.8427],
        [0.3075, 0.5505, 0.5958, 0.0369]])

In [19]:
torch.cat([tensor,tensor,tensor],dim = 1)

tensor([[0.4618, 0.3658, 0.2106, 0.7026, 0.4618, 0.3658, 0.2106, 0.7026, 0.4618,
         0.3658, 0.2106, 0.7026],
        [0.1488, 0.5192, 0.2418, 0.0043, 0.1488, 0.5192, 0.2418, 0.0043, 0.1488,
         0.5192, 0.2418, 0.0043],
        [0.3612, 0.5849, 0.8287, 0.8427, 0.3612, 0.5849, 0.8287, 0.8427, 0.3612,
         0.5849, 0.8287, 0.8427],
        [0.3075, 0.5505, 0.5958, 0.0369, 0.3075, 0.5505, 0.5958, 0.0369, 0.3075,
         0.5505, 0.5958, 0.0369]])

# Arithmatic Operation

In [20]:
#matrix multiplication
t1 = torch.rand(2,2)
t2 = torch.rand(2,2)
y1 = t1@t2.T
print(y1)
y2 = t1.matmul(t2.T)
print(y2)

tensor([[0.2627, 0.0989],
        [0.4553, 0.1342]])
tensor([[0.2627, 0.0989],
        [0.4553, 0.1342]])


In [21]:
z1 = t1*t2 #element wise multiplication

In [22]:
print(z1)

tensor([[0.1637, 0.0991],
        [0.0457, 0.0885]])


In [23]:
z2 = t1.mul(t2) #it can also done for element wise multiplication
z2

tensor([[0.1637, 0.0991],
        [0.0457, 0.0885]])

In [24]:
#sum of all elements in the matrix
agg = t1.sum()
print(agg)
print(agg.item())

tensor(2.1493)
2.149332046508789


# change values to tensor

In [25]:
ten = torch.ones(4,4)

In [26]:
ten

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
ten[:,2] = 0

In [28]:
ten

tensor([[1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.],
        [1., 1., 0., 1.]])

In [29]:
#add a number to a tensor
ten.add_(5)

tensor([[6., 6., 5., 6.],
        [6., 6., 5., 6.],
        [6., 6., 5., 6.],
        [6., 6., 5., 6.]])

In [30]:
x = np.array([[1,2],[3,4]])
tensor = torch.from_numpy(x) #convert it into tensor
y = tensor.numpy()#convert it to numpy array

In [31]:
type(x)

numpy.ndarray

In [32]:
type(tensor)

torch.Tensor

In [33]:
type(y)

numpy.ndarray